CREATE TABLE `tm_adventures` (
  `adventure_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `title` varchar(100) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `loc_name` varchar(100) NOT NULL,
  `loc_address` varchar(200) DEFAULT NULL,
  `loc_latitude` decimal(10,6) DEFAULT '0.000000',
  `loc_longitude` decimal(10,6) DEFAULT '0.000000',
  `loc_radius_km` decimal(8,3) DEFAULT '20.000',
  `loc_photo_url` varchar(200) DEFAULT NULL,
  `date_start` datetime DEFAULT NULL,
  `date_end` datetime DEFAULT NULL,
  `interest_age_min` int(11) DEFAULT NULL,
  `interest_age_max` int(11) DEFAULT NULL,
  `interest_gender` varchar(50) DEFAULT NULL,
  `interest_relationship` varchar(50) DEFAULT NULL,
  `op_budget` varchar(45) DEFAULT NULL,
  `op_accomodation` varchar(45) DEFAULT NULL,
  `op_interests` varchar(1000) DEFAULT NULL,
  `op_habbits` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`adventure_id`),
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
